### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "ilyasse analytics-service3",
  "email": "ilyasse1Test15@mail.com",
  "address": "123 Maiin Street, City, Country",
  "dateOfBirth": "1990-05-15",
  "registeredDate": "2025-10-07"
}
###